export const projects = [
  {
    title: 'Media Naranja App Concurso',
    description: "Desarrollo de una aplicación Full Stack para Almacenes La Media Naranja en Colombia, que permite el registro de los usuarios que reciben cupones por compras, cuenta con un dashboard de administración para la gestión de usuarios, tickets y posteriormente para la selección de ganadores.",
      image: [
        '/images/MNAP/0.png',
        '/images/MNAP/1.png',
        '/images/MNAP/2.png',
        '/images/MNAP/3.png',
        '/images/MNAP/4.png',
        '/images/MNAP/5.png',
        '/images/MNAP/6.png',
        '/images/MNAP/7.png',
        '/images/MNAP/8.png',
        '/images/MNAP/9.png',
        '/images/MNAP/10.png',
        ],
      tags: ['React', 'Redux', 'MaterialUI', 'JavaScript', 'PostgreSQL', 'Sequelize', 'Express', 'Node'],
    source: 'https://sorteos.lamedianaranja.com.co/',
    visit: 'https://github.com/Hermes91/MediaNaranja-Front',
    id: 0,
  },
  {
    title: 'Vivero Henry',
    description:"E-commerce de un vivero en STACK PERN. Desarrollado bajo la metodología SCRUM, implementando tecnologías como Toastify, Landbot, PayPal Sandbox, Fortawesome, LocalStorage, Auth0, FormSpark, Cookie-parser, CORS, dotenv, jsonwebtoken, Cloudinary.",
    image: [
      '/images/VH/01.png',
      '/images/VH/02.png',
      '/images/VH/03.png',
      '/images/VH/04.png',
      '/images/VH/05.png',
      '/images/VH/06.png',
      '/images/VH/07.png',
      '/images/VH/08.png',
      '/images/VH/09.png',
      '/images/VH/10.png',
      '/images/VH/11.png',
      '/images/VH/12.png',
      '/images/VH/13.png',
      '/images/VH/14.png',
      '/images/VH/15.png',
      '/images/VH/16.png',
      '/images/VH/17.png',
      ],
    tags: ['React', 'Redux', 'Bootstrap', 'MaterialUI', 'Express', 'PostgreSQL', 'Sequelize', 'Node'],
    source: 'https://vivero-henry.vercel.app/',
    visit: 'https://github.com/bosxch/PF-Henry',
    id: 1,
  },
  {
    title: 'BEST FRIEND FINDER',
    description: "Proyecto Individual de la temática Dogs, realizado en el bootcamp Henry. Este proyecto consiste en una single page aplication donde el usuario puede: Buscar razas, aplicar filtros y ordenamientos combinados, y crear su propia raza.",
    image: [
      '/images/BFF/01.png',
      '/images/BFF/02.png',
      '/images/BFF/03.png',
      '/images/BFF/04.png',
      '/images/BFF/05.png',
      '/images/BFF/06.png',
      '/images/BFF/07.png',
      '/images/BFF/08.png',
      '/images/BFF/09.png',
      '/images/BFF/10.png',
      '/images/BFF/11.png',
      ],
      tags: ['React','Redux','Css','Html','Node.js','Express','Sequelize','PostgreSQL'],
    source: 'https://best-friend-finder.vercel.app/',
    visit: 'https://github.com/bosxch/PI-HenryDogs',
    id: 2,
  },

];

export const TimeLineData = [
  { year: 2022, text: 'Aprendí las bases de la programación en pseudocódigo.', },
  { year: 2022, text: 'Comencé a cursar el Bootcamp Henry en la carrera Full Stack Web Developer.', },
  { year: 2022, text: 'En Diciembre comencé a trabajar en Microingeniería Aplicada SAS como Profesional Independiente. Sigo en este puesto actualmente.', },
  { year: 2023, text: 'En Febrero terminé el Bootcamp Henry con la aprobación del proyecto Vivero Henry.', },
  { year: 2023, text: 'Formé parte del equipo de desarrollo de la aplicación para sorteos para la empresa Almacenes La Media Naranja como Profesional Independiente.', },
];

export const data = [
  { number: 3, text: 'Proyectos Desarrollados'},
  { number: 3, text: 'Clientes Satisfechos', },
  { number: 1900, text: 'Github Commits', },
  { number: 5000, text: 'Github Stars', }
];